[tool.poetry]
name = "arch"
version = "0.1.0"
description = ""
authors = ["Julio Arias"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
ansible = "^2.10.6"
neovim = "^0.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
