host_systemd_user_services:
  - tarsnap.timer

host_packages:
  - amd-ucode
  - xf86-video-amdgpu
  - vulkan-radeon
  - steam
  - liquidctl

host_aur_packages:
  - it87-dkms-git
  - bottles
  - obs-vkcapture-git
  - lib32-obs-vkcapture-git
  - xboxdrv
  - cemu-bin

video_driver: amdgpu
