host_packages:
  - amd-ucode
  - xf86-video-amdgpu
  - vulkan-radeon
  - steam
  - liquidctl

aur_packages:
  - it87-dkms-git
  - bottles
  - obs-vkcapture-git
  - lib32-obs-vkcapture-git
    #- protonup-qt-bin
  - xboxdrv
  - cemu-bin
video_driver: amdgpu
